      MODULE NMPRD4P
      USE SIZES, ONLY: DPSIZE
      USE NMPRD4,ONLY: VRBL
      IMPLICIT NONE
      SAVE
      REAL(KIND=DPSIZE), DIMENSION (:),POINTER ::COM
      REAL(KIND=DPSIZE), POINTER ::CL,VC,VP,Q2,VP2,Q3,V1,V2,V3,Q,S1,S2
      REAL(KIND=DPSIZE), POINTER ::S3,Y,A00032,A00034,A00035,A00036
      CONTAINS
      SUBROUTINE ASSOCNMPRD4
      COM=>VRBL
      CL=>COM(00001);VC=>COM(00002);VP=>COM(00003);Q2=>COM(00004)
      VP2=>COM(00005);Q3=>COM(00006);V1=>COM(00007);V2=>COM(00008)
      V3=>COM(00009);Q=>COM(00010);S1=>COM(00011);S2=>COM(00012)
      S3=>COM(00013);Y=>COM(00014);A00032=>COM(00015)
      A00034=>COM(00016);A00035=>COM(00017);A00036=>COM(00018)
      END SUBROUTINE ASSOCNMPRD4
      END MODULE NMPRD4P
      SUBROUTINE PK(ICALL,IDEF,THETA,IREV,EVTREC,NVNT,INDXS,IRGG,GG,NETAS)      
      USE NMPRD4P
      USE SIZES,     ONLY: DPSIZE,ISIZE
      USE PRDIMS,    ONLY: GPRD,HPRD,GERD,HERD,GPKD
      USE NMPRD_REAL,ONLY: ETA,EPS                                            
      USE NMPRD_INT, ONLY: MSEC=>ISECDER,MFIRST=>IFRSTDER,COMACT,COMSAV,IFIRSTEM
      USE NMPRD_INT, ONLY: MDVRES,ETASXI,NPDE_MODE
      USE NMPRD_REAL, ONLY: DV_LOQ
      USE NMPRD_INT, ONLY: IQUIT
      USE PROCM_INT, ONLY: NEWIND=>PNEWIF                                       
      USE NMBAYES_REAL, ONLY: LDF                                             
      IMPLICIT REAL(KIND=DPSIZE) (A-Z)                                          
      REAL(KIND=DPSIZE) :: EVTREC                                               
      SAVE
      INTEGER(KIND=ISIZE) :: FIRSTEM
      INTEGER(KIND=ISIZE) :: ICALL,IDEF,IREV,NVNT,INDXS,IRGG,NETAS              
      DIMENSION :: IDEF(7,*),THETA(*),EVTREC(IREV,*),INDXS(*),GG(IRGG,GPKD+1,*) 
      FIRSTEM=IFIRSTEM
      IF (ICALL <= 1) THEN                                                      
      CALL ASSOCNMPRD4
      IDEF(  1,001)= -9
      IDEF(  1,002)= -1
      IDEF(  1,003)=  0
      IDEF(  1,004)=  0
      IDEF(  2,003)=  0
      IDEF(  2,004)=  0
      IDEF(  3,001)=  7
      IDEF(  3,002)=  8
      IDEF(  3,003)=  9
      CALL GETETA(ETA)                                                          
      IF (IQUIT == 1) RETURN                                                    
      RETURN                                                                    
      ENDIF                                                                     
      IF (NEWIND /= 2) THEN
      IF (ICALL == 4) THEN
      CALL SIMETA(ETA)
      ELSE
      CALL GETETA(ETA)
      ENDIF
      IF (IQUIT == 1) RETURN
      ENDIF
 !  level            0
      B00001=DEXP(ETA(001)) 
      CL=THETA(001)*B00001 
      B00002=DEXP(ETA(002)) 
      VC=THETA(002)*B00002 
      VP=THETA(003) 
      Q2=THETA(004) 
      VP2=THETA(005) 
      Q3=THETA(006) 
      V1=VC 
      V2=VP 
      V3=VP2 
      Q=Q2 
      S1=V1 
      S2=V2 
      S3=V3 
      IF (FIRSTEM == 1) THEN
!                      A00032 = DERIVATIVE OF CL W.R.T. ETA(001)
      A00032=THETA(001)*B00001 
!                      A00034 = DERIVATIVE OF VC W.R.T. ETA(002)
      A00034=THETA(002)*B00002 
!                      A00035 = DERIVATIVE OF V1 W.R.T. ETA(002)
      A00035=A00034 
!                      A00036 = DERIVATIVE OF S1 W.R.T. ETA(002)
      A00036=A00035 
      GG(001,1,1)=CL
      GG(001,002,1)=A00032
      GG(002,1,1)=V1
      GG(002,003,1)=A00035
      GG(003,1,1)=Q2
      GG(004,1,1)=V2
      GG(005,1,1)=Q3
      GG(006,1,1)=V3
      GG(007,1,1)=S1
      GG(007,003,1)=A00036
      GG(008,1,1)=S2
      GG(009,1,1)=S3
      ELSE
      GG(001,1,1)=CL
      GG(002,1,1)=V1
      GG(003,1,1)=Q2
      GG(004,1,1)=V2
      GG(005,1,1)=Q3
      GG(006,1,1)=V3
      GG(007,1,1)=S1
      GG(008,1,1)=S2
      GG(009,1,1)=S3
      ENDIF
      RETURN
      END
      SUBROUTINE ERROR (ICALL,IDEF,THETA,IREV,EVTREC,NVNT,INDXS,F,G,HH)       
      USE NMPRD4P
      USE SIZES,     ONLY: DPSIZE,ISIZE
      USE PRDIMS,    ONLY: GPRD,HPRD,GERD,HERD,GPKD
      USE NMPRD_REAL,ONLY: ETA,EPS                                            
      USE NMPRD_INT, ONLY: MSEC=>ISECDER,MFIRST=>IFRSTDER,IQUIT,IFIRSTEM
      USE NMPRD_INT, ONLY: MDVRES,ETASXI,NPDE_MODE
      USE NMPRD_REAL, ONLY: DV_LOQ
      USE NMPRD_INT, ONLY: NEWL2
      USE PROCM_INT, ONLY: NEWIND=>PNEWIF                                       
      IMPLICIT REAL(KIND=DPSIZE) (A-Z)                                        
      REAL(KIND=DPSIZE) :: EVTREC                                             
      SAVE
      INTEGER(KIND=ISIZE) :: ICALL,IDEF,IREV,NVNT,INDXS                       
      DIMENSION :: IDEF(*),THETA(*),EVTREC(IREV,*),INDXS(*)                   
      REAL(KIND=DPSIZE) :: G(GERD,*),HH(HERD,*)                               
      INTEGER(KIND=ISIZE) :: FIRSTEM
      FIRSTEM=IFIRSTEM
      IF (ICALL <= 1) THEN                                                    
      CALL ASSOCNMPRD4
      IDEF(2)=2
      IDEF(1)=1
      HH(1,1)=1.0D0
      IDEF(3)=000
      RETURN
      ENDIF
      IF (ICALL == 4) THEN
      IF (NEWL2 == 1) THEN
      CALL SIMEPS(EPS)
      IF (IQUIT == 1) RETURN
      ENDIF
      ENDIF
 !  level            0
      B00001=1.D0+EPS(001) 
      Y=F*B00001 
      IF (FIRSTEM == 1) THEN !1
      ENDIF !1
      F=Y
      RETURN
      END
      SUBROUTINE FSIZESR(NAME_FSIZES,F_SIZES)
      USE SIZES, ONLY: ISIZE
      INTEGER(KIND=ISIZE), DIMENSION(*) :: F_SIZES
      CHARACTER(LEN=*),    DIMENSION(*) :: NAME_FSIZES
      NAME_FSIZES(01)='LTH'; F_SIZES(01)=6
      NAME_FSIZES(02)='LVR'; F_SIZES(02)=3
      NAME_FSIZES(03)='LVR2'; F_SIZES(03)=0
      NAME_FSIZES(04)='LPAR'; F_SIZES(04)=10
      NAME_FSIZES(05)='LPAR3'; F_SIZES(05)=0
      NAME_FSIZES(06)='NO'; F_SIZES(06)=0
      NAME_FSIZES(07)='MMX'; F_SIZES(07)=1
      NAME_FSIZES(08)='LNP4'; F_SIZES(08)=0
      NAME_FSIZES(09)='LSUPP'; F_SIZES(09)=1
      NAME_FSIZES(10)='LIM7'; F_SIZES(10)=0
      NAME_FSIZES(11)='LWS3'; F_SIZES(11)=0
      NAME_FSIZES(12)='MAXIDS'; F_SIZES(12)=6
      NAME_FSIZES(13)='LIM1'; F_SIZES(13)=0
      NAME_FSIZES(14)='LIM2'; F_SIZES(14)=0
      NAME_FSIZES(15)='LIM3'; F_SIZES(15)=0
      NAME_FSIZES(16)='LIM4'; F_SIZES(16)=0
      NAME_FSIZES(17)='LIM5'; F_SIZES(17)=0
      NAME_FSIZES(18)='LIM6'; F_SIZES(18)=0
      NAME_FSIZES(19)='LIM8'; F_SIZES(19)=0
      NAME_FSIZES(20)='LIM11'; F_SIZES(20)=0
      NAME_FSIZES(21)='LIM13'; F_SIZES(21)=0
      NAME_FSIZES(22)='LIM15'; F_SIZES(22)=0
      NAME_FSIZES(23)='LIM16'; F_SIZES(23)=0
      NAME_FSIZES(24)='MAXRECID'; F_SIZES(24)=200
      NAME_FSIZES(25)='PC'; F_SIZES(25)=30
      NAME_FSIZES(26)='PCT'; F_SIZES(26)=30
      NAME_FSIZES(27)='PIR'; F_SIZES(27)=700
      NAME_FSIZES(28)='PD'; F_SIZES(28)=50
      NAME_FSIZES(29)='PAL'; F_SIZES(29)=50
      NAME_FSIZES(30)='MAXFCN'; F_SIZES(30)=1000000
      NAME_FSIZES(31)='MAXIC'; F_SIZES(31)=90
      NAME_FSIZES(32)='PG'; F_SIZES(32)=80
      NAME_FSIZES(33)='NPOPMIXMAX'; F_SIZES(33)=0
      NAME_FSIZES(34)='MAXOMEG'; F_SIZES(34)=2
      NAME_FSIZES(35)='MAXPTHETA'; F_SIZES(35)=7
      NAME_FSIZES(36)='MAXITER'; F_SIZES(36)=20
      NAME_FSIZES(37)='ISAMPLEMAX'; F_SIZES(37)=0
      NAME_FSIZES(38)='DIMTMP'; F_SIZES(38)=0
      NAME_FSIZES(39)='DIMCNS'; F_SIZES(39)=0
      NAME_FSIZES(40)='DIMNEW'; F_SIZES(40)=0
      NAME_FSIZES(41)='PDT'; F_SIZES(41)=9
      NAME_FSIZES(42)='LADD_MAX'; F_SIZES(42)=0
      NAME_FSIZES(43)='MAXSIDL'; F_SIZES(43)=0
      NAME_FSIZES(44)='NTT'; F_SIZES(44)=6
      NAME_FSIZES(45)='NOMEG'; F_SIZES(45)=2
      NAME_FSIZES(46)='NSIGM'; F_SIZES(46)=1
      NAME_FSIZES(47)='PPDT'; F_SIZES(47)=1
      RETURN
      END SUBROUTINE FSIZESR
      SUBROUTINE MUMODEL2(THETA,MU_,ICALL,IDEF,NEWIND,&
      EVTREC,DATREC,IREV,NVNT,INDXS,F,G,H,IRGG,GG,NETAS)
      USE NMPRD4P
      USE SIZES,     ONLY: DPSIZE,ISIZE
      USE PRDIMS,    ONLY: GPRD,HPRD,GERD,HERD,GPKD
      USE NMPRD_REAL,ONLY: ETA,EPS
      USE NMPRD_INT, ONLY: MSEC=>ISECDER,MFIRST=>IFRSTDER,COMACT,COMSAV,IFIRSTEM
      USE NMPRD_INT, ONLY: MDVRES,ETASXI,NPDE_MODE
      USE NMPRD_REAL, ONLY: DV_LOQ
      USE NMPRD_INT, ONLY: IQUIT
      USE NMBAYES_REAL, ONLY: LDF
      IMPLICIT REAL(KIND=DPSIZE) (A-Z)
      REAL(KIND=DPSIZE)   :: MU_(*)
      INTEGER NEWIND
      REAL(KIND=DPSIZE) :: EVTREC
      SAVE
      INTEGER(KIND=ISIZE) :: FIRSTEM
      INTEGER(KIND=ISIZE) :: ICALL,IDEF,IREV,NVNT,INDXS,IRGG,NETAS
      DIMENSION :: IDEF(7,*),THETA(*),EVTREC(IREV,*),INDXS(*),GG(IRGG,GPKD+1,*)
      RETURN
      END
