test_that("job progress touches heartbeat and log on gradient", {
  job_path <- tempfile("nm_prog_")
  dir.create(job_path)
  on.exit(unlink(job_path, recursive = TRUE), add = TRUE)
  .nm_job_progress_init(job_path)
  on.exit(.nm_job_progress_clear(), add = TRUE)
  .nm_job_progress_grad(1L, c(a = 1, b = 2), prefix = "Test", print_every = 1L)
  expect_true(file.exists(file.path(job_path, "worker.heartbeat")))
  expect_true(file.exists(file.path(job_path, "worker.progress")))
  log_txt <- readLines(file.path(job_path, "worker.log"), warn = FALSE)
  expect_true(any(grepl("gradient evaluation 1", log_txt, ignore.case = TRUE)))
  expect_true(.nm_job_progress_active(job_path, idle_sec = 60))
})

test_that("wrap_grad_trace records progress without printing when print_every is 0", {
  job_path <- tempfile("nm_prog2_")
  dir.create(job_path)
  on.exit(unlink(job_path, recursive = TRUE), add = TRUE)
  .nm_job_progress_init(job_path)
  on.exit(.nm_job_progress_clear(), add = TRUE)
  gr <- .nm_wrap_grad_trace(function(x) x * 0 + 1, 0L, c("p1", "p2"), prefix = "Pop")
  gr(c(1, 2))
  expect_true(file.exists(file.path(job_path, "worker.heartbeat")))
  expect_false(file.exists(file.path(job_path, "worker.log")))
})
