$PROBLEM Pilot ADVAN=2 TRANS=2
$SUBROUTINE ADVAN2 TRANS2
$INPUT ID TIME AMT DV MDV EVID CMT SS II
$DATA design.csv IGNORE=@
$THETA (0,1) ; CL
 (0,10) ; V
 (0,1) ; KA
 (0,0.5) ; ALAG
$OMEGA 0.09
 0.09
$SIGMA 0.1
 0.5
$PK
 CL = THETA(1) * EXP(ETA(1))
 V = THETA(2) * EXP(ETA(2))
 KA = THETA(3)
 ALAG1 = THETA(4)
$ERROR
 Y = F * (1 + ERR(1)) + ERR(2)
$EST METHOD=0 MAXEVAL=0
$SIM (12345 NEW) ONLYSIM NSUB=1
$TABLE ID TIME AMT DV MDV EVID CMT SS II ONEHEADER NOPRINT FILE=simtab
