// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// liberation_native_optimizer
Rcpp::List liberation_native_optimizer(const Rcpp::Function& objective, const Rcpp::Function& gradient, const Rcpp::NumericVector& start, const Rcpp::NumericVector& lower, const Rcpp::NumericVector& upper, int maxit, double tolerance, int trace);
RcppExport SEXP _LibeRation_liberation_native_optimizer(SEXP objectiveSEXP, SEXP gradientSEXP, SEXP startSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP maxitSEXP, SEXP toleranceSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type objective(objectiveSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Function& >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_native_optimizer(objective, gradient, start, lower, upper, maxit, tolerance, trace));
    return rcpp_result_gen;
END_RCPP
}
// liberation_population_objective_create
SEXP liberation_population_objective_create(SEXP engine_pointer, const Rcpp::List& subject_data, const Rcpp::List& primary_tape_pointers, const Rcpp::List& curvature_tape_pointers, const Rcpp::List& config);
RcppExport SEXP _LibeRation_liberation_population_objective_create(SEXP engine_pointerSEXP, SEXP subject_dataSEXP, SEXP primary_tape_pointersSEXP, SEXP curvature_tape_pointersSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type subject_data(subject_dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type primary_tape_pointers(primary_tape_pointersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type curvature_tape_pointers(curvature_tape_pointersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_population_objective_create(engine_pointer, subject_data, primary_tape_pointers, curvature_tape_pointers, config));
    return rcpp_result_gen;
END_RCPP
}
// liberation_population_objective_value
double liberation_population_objective_value(SEXP pointer, const Rcpp::NumericVector& encoded);
RcppExport SEXP _LibeRation_liberation_population_objective_value(SEXP pointerSEXP, SEXP encodedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type encoded(encodedSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_population_objective_value(pointer, encoded));
    return rcpp_result_gen;
END_RCPP
}
// liberation_population_objective_gradient
Rcpp::NumericVector liberation_population_objective_gradient(SEXP pointer, const Rcpp::NumericVector& encoded);
RcppExport SEXP _LibeRation_liberation_population_objective_gradient(SEXP pointerSEXP, SEXP encodedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type encoded(encodedSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_population_objective_gradient(pointer, encoded));
    return rcpp_result_gen;
END_RCPP
}
// liberation_population_objective_state
Rcpp::List liberation_population_objective_state(SEXP pointer, const Rcpp::NumericVector& encoded);
RcppExport SEXP _LibeRation_liberation_population_objective_state(SEXP pointerSEXP, SEXP encodedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type encoded(encodedSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_population_objective_state(pointer, encoded));
    return rcpp_result_gen;
END_RCPP
}
// liberation_population_objective_telemetry
Rcpp::List liberation_population_objective_telemetry(SEXP pointer);
RcppExport SEXP _LibeRation_liberation_population_objective_telemetry(SEXP pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pointer(pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_population_objective_telemetry(pointer));
    return rcpp_result_gen;
END_RCPP
}
// liberation_engine_create
SEXP liberation_engine_create(const Rcpp::List& specification);
RcppExport SEXP _LibeRation_liberation_engine_create(SEXP specificationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type specification(specificationSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_engine_create(specification));
    return rcpp_result_gen;
END_RCPP
}
// liberation_engine_simulate
Rcpp::List liberation_engine_simulate(SEXP engine_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma);
RcppExport SEXP _LibeRation_liberation_engine_simulate(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_engine_simulate(engine_pointer, data, theta, eta, sigma));
    return rcpp_result_gen;
END_RCPP
}
// liberation_engine_hmm_filter
Rcpp::List liberation_engine_hmm_filter(SEXP engine_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma);
RcppExport SEXP _LibeRation_liberation_engine_hmm_filter(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_engine_hmm_filter(engine_pointer, data, theta, eta, sigma));
    return rcpp_result_gen;
END_RCPP
}
// liberation_engine_kalman_filter
Rcpp::List liberation_engine_kalman_filter(SEXP engine_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma);
RcppExport SEXP _LibeRation_liberation_engine_kalman_filter(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_engine_kalman_filter(engine_pointer, data, theta, eta, sigma));
    return rcpp_result_gen;
END_RCPP
}
// liberation_engine_kalman_simulate
Rcpp::NumericVector liberation_engine_kalman_simulate(SEXP engine_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma, const Rcpp::NumericMatrix& process_normals, const Rcpp::NumericVector& observation_normals);
RcppExport SEXP _LibeRation_liberation_engine_kalman_simulate(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP, SEXP process_normalsSEXP, SEXP observation_normalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type process_normals(process_normalsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type observation_normals(observation_normalsSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_engine_kalman_simulate(engine_pointer, data, theta, eta, sigma, process_normals, observation_normals));
    return rcpp_result_gen;
END_RCPP
}
// liberation_engine_derivative
Rcpp::NumericVector liberation_engine_derivative(SEXP engine_pointer, const Rcpp::DataFrame& data, int row, int subject, double time, const Rcpp::NumericVector& state, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma);
RcppExport SEXP _LibeRation_liberation_engine_derivative(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP rowSEXP, SEXP subjectSEXP, SEXP timeSEXP, SEXP stateSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type row(rowSEXP);
    Rcpp::traits::input_parameter< int >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_engine_derivative(engine_pointer, data, row, subject, time, state, theta, eta, sigma));
    return rcpp_result_gen;
END_RCPP
}
// liberation_matrix_exp
Rcpp::NumericMatrix liberation_matrix_exp(const Rcpp::NumericMatrix& matrix, double dt);
RcppExport SEXP _LibeRation_liberation_matrix_exp(SEXP matrixSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_matrix_exp(matrix, dt));
    return rcpp_result_gen;
END_RCPP
}
// liberation_advan_matrix
Rcpp::List liberation_advan_matrix(int advan, const Rcpp::List& parameters);
RcppExport SEXP _LibeRation_liberation_advan_matrix(SEXP advanSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_advan_matrix(advan, parameters));
    return rcpp_result_gen;
END_RCPP
}
// liberation_prediction_tape_create
SEXP liberation_prediction_tape_create(SEXP engine_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma);
RcppExport SEXP _LibeRation_liberation_prediction_tape_create(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_prediction_tape_create(engine_pointer, data, theta, eta, sigma));
    return rcpp_result_gen;
END_RCPP
}
// liberation_prediction_tape_info
Rcpp::List liberation_prediction_tape_info(SEXP tape_pointer);
RcppExport SEXP _LibeRation_liberation_prediction_tape_info(SEXP tape_pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_prediction_tape_info(tape_pointer));
    return rcpp_result_gen;
END_RCPP
}
// liberation_prediction_tape_new_dynamic
Rcpp::NumericVector liberation_prediction_tape_new_dynamic(SEXP tape_pointer, const Rcpp::DataFrame& data);
RcppExport SEXP _LibeRation_liberation_prediction_tape_new_dynamic(SEXP tape_pointerSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_prediction_tape_new_dynamic(tape_pointer, data));
    return rcpp_result_gen;
END_RCPP
}
// liberation_fo_tape_new_dynamic
Rcpp::NumericVector liberation_fo_tape_new_dynamic(SEXP tape_pointer, const Rcpp::DataFrame& data);
RcppExport SEXP _LibeRation_liberation_fo_tape_new_dynamic(SEXP tape_pointerSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_fo_tape_new_dynamic(tape_pointer, data));
    return rcpp_result_gen;
END_RCPP
}
// liberation_prediction_tape_eval
Rcpp::List liberation_prediction_tape_eval(SEXP tape_pointer, const Rcpp::NumericVector& point, bool jacobian);
RcppExport SEXP _LibeRation_liberation_prediction_tape_eval(SEXP tape_pointerSEXP, SEXP pointSEXP, SEXP jacobianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type point(pointSEXP);
    Rcpp::traits::input_parameter< bool >::type jacobian(jacobianSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_prediction_tape_eval(tape_pointer, point, jacobian));
    return rcpp_result_gen;
END_RCPP
}
// liberation_prediction_tape_eval_subset
Rcpp::List liberation_prediction_tape_eval_subset(SEXP tape_pointer, const Rcpp::NumericVector& point, const Rcpp::IntegerVector& columns);
RcppExport SEXP _LibeRation_liberation_prediction_tape_eval_subset(SEXP tape_pointerSEXP, SEXP pointSEXP, SEXP columnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type point(pointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type columns(columnsSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_prediction_tape_eval_subset(tape_pointer, point, columns));
    return rcpp_result_gen;
END_RCPP
}
// liberation_matrix_exp_pade
Rcpp::NumericMatrix liberation_matrix_exp_pade(const Rcpp::NumericMatrix& matrix, double dt);
RcppExport SEXP _LibeRation_liberation_matrix_exp_pade(SEXP matrixSEXP, SEXP dtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_matrix_exp_pade(matrix, dt));
    return rcpp_result_gen;
END_RCPP
}
// liberation_fo_tape_create
SEXP liberation_fo_tape_create(SEXP engine_pointer, SEXP prediction_tape_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericVector& sigma, const Rcpp::NumericVector& omega);
RcppExport SEXP _LibeRation_liberation_fo_tape_create(SEXP engine_pointerSEXP, SEXP prediction_tape_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP sigmaSEXP, SEXP omegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prediction_tape_pointer(prediction_tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type omega(omegaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_fo_tape_create(engine_pointer, prediction_tape_pointer, data, theta, sigma, omega));
    return rcpp_result_gen;
END_RCPP
}
// liberation_curvature_tape_create
SEXP liberation_curvature_tape_create(SEXP engine_pointer, SEXP prediction_tape_pointer, SEXP objective_tape_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericVector& eta, const Rcpp::NumericVector& sigma, const Rcpp::NumericVector& omega, const std::string& approximation);
RcppExport SEXP _LibeRation_liberation_curvature_tape_create(SEXP engine_pointerSEXP, SEXP prediction_tape_pointerSEXP, SEXP objective_tape_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP, SEXP omegaSEXP, SEXP approximationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prediction_tape_pointer(prediction_tape_pointerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type objective_tape_pointer(objective_tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type approximation(approximationSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_curvature_tape_create(engine_pointer, prediction_tape_pointer, objective_tape_pointer, data, theta, eta, sigma, omega, approximation));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_create
SEXP liberation_objective_tape_create(SEXP engine_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma, const Rcpp::NumericVector& omega, bool interaction);
RcppExport SEXP _LibeRation_liberation_objective_tape_create(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP, SEXP omegaSEXP, SEXP interactionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< bool >::type interaction(interactionSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_create(engine_pointer, data, theta, eta, sigma, omega, interaction));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_eval
Rcpp::List liberation_objective_tape_eval(SEXP tape_pointer, const Rcpp::NumericVector& point, bool gradient, bool hessian);
RcppExport SEXP _LibeRation_liberation_objective_tape_eval(SEXP tape_pointerSEXP, SEXP pointSEXP, SEXP gradientSEXP, SEXP hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type point(pointSEXP);
    Rcpp::traits::input_parameter< bool >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< bool >::type hessian(hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_eval(tape_pointer, point, gradient, hessian));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_info
Rcpp::List liberation_objective_tape_info(SEXP tape_pointer);
RcppExport SEXP _LibeRation_liberation_objective_tape_info(SEXP tape_pointerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_info(tape_pointer));
    return rcpp_result_gen;
END_RCPP
}
// liberation_hmc_target_eval
Rcpp::List liberation_hmc_target_eval(SEXP tape_pointer, const Rcpp::NumericVector& q, const Rcpp::List& config);
RcppExport SEXP _LibeRation_liberation_hmc_target_eval(SEXP tape_pointerSEXP, SEXP qSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_hmc_target_eval(tape_pointer, q, config));
    return rcpp_result_gen;
END_RCPP
}
// liberation_hmc_sample
Rcpp::List liberation_hmc_sample(SEXP tape_pointer, const Rcpp::List& config, const std::string& method, int n_warmup, int n_sample, int n_thin, int n_chains, double seed, double step_size, double target_acceptance, bool adapt_mass, int n_leapfrog, int max_depth, double divergence_threshold, int print_every);
RcppExport SEXP _LibeRation_liberation_hmc_sample(SEXP tape_pointerSEXP, SEXP configSEXP, SEXP methodSEXP, SEXP n_warmupSEXP, SEXP n_sampleSEXP, SEXP n_thinSEXP, SEXP n_chainsSEXP, SEXP seedSEXP, SEXP step_sizeSEXP, SEXP target_acceptanceSEXP, SEXP adapt_massSEXP, SEXP n_leapfrogSEXP, SEXP max_depthSEXP, SEXP divergence_thresholdSEXP, SEXP print_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type n_warmup(n_warmupSEXP);
    Rcpp::traits::input_parameter< int >::type n_sample(n_sampleSEXP);
    Rcpp::traits::input_parameter< int >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< int >::type n_chains(n_chainsSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type target_acceptance(target_acceptanceSEXP);
    Rcpp::traits::input_parameter< bool >::type adapt_mass(adapt_massSEXP);
    Rcpp::traits::input_parameter< int >::type n_leapfrog(n_leapfrogSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< double >::type divergence_threshold(divergence_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type print_every(print_everySEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_hmc_sample(tape_pointer, config, method, n_warmup, n_sample, n_thin, n_chains, seed, step_size, target_acceptance, adapt_mass, n_leapfrog, max_depth, divergence_threshold, print_every));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_eta_values
Rcpp::NumericVector liberation_objective_tape_eta_values(SEXP tape_pointer, const Rcpp::NumericVector& point, const Rcpp::IntegerVector& eta_positions, const Rcpp::NumericMatrix& eta);
RcppExport SEXP _LibeRation_liberation_objective_tape_eta_values(SEXP tape_pointerSEXP, SEXP pointSEXP, SEXP eta_positionsSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type point(pointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type eta_positions(eta_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_eta_values(tape_pointer, point, eta_positions, eta));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_collection_values
Rcpp::NumericVector liberation_objective_tape_collection_values(const Rcpp::List& tape_pointers, const Rcpp::NumericMatrix& points);
RcppExport SEXP _LibeRation_liberation_objective_tape_collection_values(SEXP tape_pointersSEXP, SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type tape_pointers(tape_pointersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_collection_values(tape_pointers, points));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_collection_gradients
Rcpp::NumericMatrix liberation_objective_tape_collection_gradients(const Rcpp::List& tape_pointers, const Rcpp::NumericMatrix& points);
RcppExport SEXP _LibeRation_liberation_objective_tape_collection_gradients(SEXP tape_pointersSEXP, SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type tape_pointers(tape_pointersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_collection_gradients(tape_pointers, points));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_hessian_subset
Rcpp::NumericMatrix liberation_objective_tape_hessian_subset(SEXP tape_pointer, const Rcpp::NumericVector& point, const Rcpp::IntegerVector& row_positions, const Rcpp::IntegerVector& column_positions);
RcppExport SEXP _LibeRation_liberation_objective_tape_hessian_subset(SEXP tape_pointerSEXP, SEXP pointSEXP, SEXP row_positionsSEXP, SEXP column_positionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type point(pointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_positions(row_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type column_positions(column_positionsSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_hessian_subset(tape_pointer, point, row_positions, column_positions));
    return rcpp_result_gen;
END_RCPP
}
// liberation_nested_population_gradient
Rcpp::List liberation_nested_population_gradient(const Rcpp::List& objective_tapes, const Rcpp::List& curvature_tapes, const Rcpp::NumericMatrix& points, const Rcpp::IntegerVector& eta_positions, const Rcpp::IntegerVector& population_positions, const Rcpp::NumericMatrix& transform);
RcppExport SEXP _LibeRation_liberation_nested_population_gradient(SEXP objective_tapesSEXP, SEXP curvature_tapesSEXP, SEXP pointsSEXP, SEXP eta_positionsSEXP, SEXP population_positionsSEXP, SEXP transformSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type objective_tapes(objective_tapesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type curvature_tapes(curvature_tapesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type eta_positions(eta_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type population_positions(population_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type transform(transformSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_nested_population_gradient(objective_tapes, curvature_tapes, points, eta_positions, population_positions, transform));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_eta_mode
Rcpp::List liberation_objective_tape_eta_mode(SEXP tape_pointer, const Rcpp::NumericVector& point, const Rcpp::IntegerVector& eta_positions, const Rcpp::NumericVector& start, int maxit, double tolerance, bool exact_hessian);
RcppExport SEXP _LibeRation_liberation_objective_tape_eta_mode(SEXP tape_pointerSEXP, SEXP pointSEXP, SEXP eta_positionsSEXP, SEXP startSEXP, SEXP maxitSEXP, SEXP toleranceSEXP, SEXP exact_hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type point(pointSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type eta_positions(eta_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type exact_hessian(exact_hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_eta_mode(tape_pointer, point, eta_positions, start, maxit, tolerance, exact_hessian));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_eta_modes
Rcpp::List liberation_objective_tape_eta_modes(const Rcpp::List& tape_pointers, const Rcpp::NumericMatrix& points, const Rcpp::IntegerVector& eta_positions, const Rcpp::NumericMatrix& starts, int maxit, double tolerance, bool exact_hessian);
RcppExport SEXP _LibeRation_liberation_objective_tape_eta_modes(SEXP tape_pointersSEXP, SEXP pointsSEXP, SEXP eta_positionsSEXP, SEXP startsSEXP, SEXP maxitSEXP, SEXP toleranceSEXP, SEXP exact_hessianSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type tape_pointers(tape_pointersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type eta_positions(eta_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< bool >::type exact_hessian(exact_hessianSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_eta_modes(tape_pointers, points, eta_positions, starts, maxit, tolerance, exact_hessian));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_point_gradients
Rcpp::List liberation_objective_tape_point_gradients(SEXP tape_pointer, const Rcpp::NumericMatrix& points);
RcppExport SEXP _LibeRation_liberation_objective_tape_point_gradients(SEXP tape_pointerSEXP, SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type tape_pointer(tape_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_point_gradients(tape_pointer, points));
    return rcpp_result_gen;
END_RCPP
}
// liberation_objective_tape_eta_metropolis
Rcpp::List liberation_objective_tape_eta_metropolis(const Rcpp::List& tape_pointers, const Rcpp::NumericMatrix& points, const Rcpp::IntegerVector& eta_positions, const Rcpp::NumericMatrix& current_eta, const Rcpp::List& proposal_roots, const Rcpp::NumericMatrix& normals, const Rcpp::NumericVector& log_uniforms, int mcmc_steps, double step_scale);
RcppExport SEXP _LibeRation_liberation_objective_tape_eta_metropolis(SEXP tape_pointersSEXP, SEXP pointsSEXP, SEXP eta_positionsSEXP, SEXP current_etaSEXP, SEXP proposal_rootsSEXP, SEXP normalsSEXP, SEXP log_uniformsSEXP, SEXP mcmc_stepsSEXP, SEXP step_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type tape_pointers(tape_pointersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type eta_positions(eta_positionsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type current_eta(current_etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type proposal_roots(proposal_rootsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type log_uniforms(log_uniformsSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc_steps(mcmc_stepsSEXP);
    Rcpp::traits::input_parameter< double >::type step_scale(step_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_objective_tape_eta_metropolis(tape_pointers, points, eta_positions, current_eta, proposal_roots, normals, log_uniforms, mcmc_steps, step_scale));
    return rcpp_result_gen;
END_RCPP
}
// liberation_mixture_component_nll
Rcpp::NumericMatrix liberation_mixture_component_nll(SEXP engine_pointer, const Rcpp::DataFrame& data, const Rcpp::NumericVector& theta, const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& sigma);
RcppExport SEXP _LibeRation_liberation_mixture_component_nll(SEXP engine_pointerSEXP, SEXP dataSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type engine_pointer(engine_pointerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(liberation_mixture_component_nll(engine_pointer, data, theta, eta, sigma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LibeRation_liberation_native_optimizer", (DL_FUNC) &_LibeRation_liberation_native_optimizer, 8},
    {"_LibeRation_liberation_population_objective_create", (DL_FUNC) &_LibeRation_liberation_population_objective_create, 5},
    {"_LibeRation_liberation_population_objective_value", (DL_FUNC) &_LibeRation_liberation_population_objective_value, 2},
    {"_LibeRation_liberation_population_objective_gradient", (DL_FUNC) &_LibeRation_liberation_population_objective_gradient, 2},
    {"_LibeRation_liberation_population_objective_state", (DL_FUNC) &_LibeRation_liberation_population_objective_state, 2},
    {"_LibeRation_liberation_population_objective_telemetry", (DL_FUNC) &_LibeRation_liberation_population_objective_telemetry, 1},
    {"_LibeRation_liberation_engine_create", (DL_FUNC) &_LibeRation_liberation_engine_create, 1},
    {"_LibeRation_liberation_engine_simulate", (DL_FUNC) &_LibeRation_liberation_engine_simulate, 5},
    {"_LibeRation_liberation_engine_hmm_filter", (DL_FUNC) &_LibeRation_liberation_engine_hmm_filter, 5},
    {"_LibeRation_liberation_engine_kalman_filter", (DL_FUNC) &_LibeRation_liberation_engine_kalman_filter, 5},
    {"_LibeRation_liberation_engine_kalman_simulate", (DL_FUNC) &_LibeRation_liberation_engine_kalman_simulate, 7},
    {"_LibeRation_liberation_engine_derivative", (DL_FUNC) &_LibeRation_liberation_engine_derivative, 9},
    {"_LibeRation_liberation_matrix_exp", (DL_FUNC) &_LibeRation_liberation_matrix_exp, 2},
    {"_LibeRation_liberation_advan_matrix", (DL_FUNC) &_LibeRation_liberation_advan_matrix, 2},
    {"_LibeRation_liberation_prediction_tape_create", (DL_FUNC) &_LibeRation_liberation_prediction_tape_create, 5},
    {"_LibeRation_liberation_prediction_tape_info", (DL_FUNC) &_LibeRation_liberation_prediction_tape_info, 1},
    {"_LibeRation_liberation_prediction_tape_new_dynamic", (DL_FUNC) &_LibeRation_liberation_prediction_tape_new_dynamic, 2},
    {"_LibeRation_liberation_fo_tape_new_dynamic", (DL_FUNC) &_LibeRation_liberation_fo_tape_new_dynamic, 2},
    {"_LibeRation_liberation_prediction_tape_eval", (DL_FUNC) &_LibeRation_liberation_prediction_tape_eval, 3},
    {"_LibeRation_liberation_prediction_tape_eval_subset", (DL_FUNC) &_LibeRation_liberation_prediction_tape_eval_subset, 3},
    {"_LibeRation_liberation_matrix_exp_pade", (DL_FUNC) &_LibeRation_liberation_matrix_exp_pade, 2},
    {"_LibeRation_liberation_fo_tape_create", (DL_FUNC) &_LibeRation_liberation_fo_tape_create, 6},
    {"_LibeRation_liberation_curvature_tape_create", (DL_FUNC) &_LibeRation_liberation_curvature_tape_create, 9},
    {"_LibeRation_liberation_objective_tape_create", (DL_FUNC) &_LibeRation_liberation_objective_tape_create, 7},
    {"_LibeRation_liberation_objective_tape_eval", (DL_FUNC) &_LibeRation_liberation_objective_tape_eval, 4},
    {"_LibeRation_liberation_objective_tape_info", (DL_FUNC) &_LibeRation_liberation_objective_tape_info, 1},
    {"_LibeRation_liberation_hmc_target_eval", (DL_FUNC) &_LibeRation_liberation_hmc_target_eval, 3},
    {"_LibeRation_liberation_hmc_sample", (DL_FUNC) &_LibeRation_liberation_hmc_sample, 15},
    {"_LibeRation_liberation_objective_tape_eta_values", (DL_FUNC) &_LibeRation_liberation_objective_tape_eta_values, 4},
    {"_LibeRation_liberation_objective_tape_collection_values", (DL_FUNC) &_LibeRation_liberation_objective_tape_collection_values, 2},
    {"_LibeRation_liberation_objective_tape_collection_gradients", (DL_FUNC) &_LibeRation_liberation_objective_tape_collection_gradients, 2},
    {"_LibeRation_liberation_objective_tape_hessian_subset", (DL_FUNC) &_LibeRation_liberation_objective_tape_hessian_subset, 4},
    {"_LibeRation_liberation_nested_population_gradient", (DL_FUNC) &_LibeRation_liberation_nested_population_gradient, 6},
    {"_LibeRation_liberation_objective_tape_eta_mode", (DL_FUNC) &_LibeRation_liberation_objective_tape_eta_mode, 7},
    {"_LibeRation_liberation_objective_tape_eta_modes", (DL_FUNC) &_LibeRation_liberation_objective_tape_eta_modes, 7},
    {"_LibeRation_liberation_objective_tape_point_gradients", (DL_FUNC) &_LibeRation_liberation_objective_tape_point_gradients, 2},
    {"_LibeRation_liberation_objective_tape_eta_metropolis", (DL_FUNC) &_LibeRation_liberation_objective_tape_eta_metropolis, 9},
    {"_LibeRation_liberation_mixture_component_nll", (DL_FUNC) &_LibeRation_liberation_mixture_component_nll, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_LibeRation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
