// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nm_bayes_mcmc_cpp
List nm_bayes_mcmc_cpp(NumericMatrix eta, NumericVector theta, NumericVector omega, NumericVector sigma, List subjects, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, int n_burn, int n_sample, int n_thin, NumericVector step_theta, NumericVector step_omega, NumericVector step_sigma, double step_eta, IntegerVector theta_prior_type, NumericVector theta_prior_mu, NumericVector theta_prior_sd, IntegerVector omega_prior_type, NumericVector omega_prior_mu, NumericVector omega_prior_sd, IntegerVector sigma_prior_type, NumericVector sigma_prior_mu, NumericVector sigma_prior_sd, LogicalVector theta_fix, CharacterVector des_lines, std::string sampler, double hmc_epsilon, int hmc_leap, int nuts_depth);
RcppExport SEXP _LibeRation_nm_bayes_mcmc_cpp(SEXP etaSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP subjectsSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP n_burnSEXP, SEXP n_sampleSEXP, SEXP n_thinSEXP, SEXP step_thetaSEXP, SEXP step_omegaSEXP, SEXP step_sigmaSEXP, SEXP step_etaSEXP, SEXP theta_prior_typeSEXP, SEXP theta_prior_muSEXP, SEXP theta_prior_sdSEXP, SEXP omega_prior_typeSEXP, SEXP omega_prior_muSEXP, SEXP omega_prior_sdSEXP, SEXP sigma_prior_typeSEXP, SEXP sigma_prior_muSEXP, SEXP sigma_prior_sdSEXP, SEXP theta_fixSEXP, SEXP des_linesSEXP, SEXP samplerSEXP, SEXP hmc_epsilonSEXP, SEXP hmc_leapSEXP, SEXP nuts_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< int >::type n_sample(n_sampleSEXP);
    Rcpp::traits::input_parameter< int >::type n_thin(n_thinSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type step_theta(step_thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type step_omega(step_omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type step_sigma(step_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type step_eta(step_etaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type theta_prior_type(theta_prior_typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_prior_mu(theta_prior_muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta_prior_sd(theta_prior_sdSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type omega_prior_type(omega_prior_typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega_prior_mu(omega_prior_muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega_prior_sd(omega_prior_sdSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sigma_prior_type(sigma_prior_typeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma_prior_mu(sigma_prior_muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma_prior_sd(sigma_prior_sdSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type theta_fix(theta_fixSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type des_lines(des_linesSEXP);
    Rcpp::traits::input_parameter< std::string >::type sampler(samplerSEXP);
    Rcpp::traits::input_parameter< double >::type hmc_epsilon(hmc_epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type hmc_leap(hmc_leapSEXP);
    Rcpp::traits::input_parameter< int >::type nuts_depth(nuts_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_bayes_mcmc_cpp(eta, theta, omega, sigma, subjects, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_burn, n_sample, n_thin, step_theta, step_omega, step_sigma, step_eta, theta_prior_type, theta_prior_mu, theta_prior_sd, omega_prior_type, omega_prior_mu, omega_prior_sd, sigma_prior_type, sigma_prior_mu, sigma_prior_sd, theta_fix, des_lines, sampler, hmc_epsilon, hmc_leap, nuts_depth));
    return rcpp_result_gen;
END_RCPP
}
// nm_subject_nll_cpp
double nm_subject_nll_cpp(NumericVector time, NumericVector amt, NumericVector rate, NumericVector f1, IntegerVector cmt, IntegerVector evid, IntegerVector ss, NumericVector ii, NumericVector dv, IntegerVector obs_idx, NumericVector eta, NumericVector theta, NumericVector omega, NumericVector sigma, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool include_omega_prior);
RcppExport SEXP _LibeRation_nm_subject_nll_cpp(SEXP timeSEXP, SEXP amtSEXP, SEXP rateSEXP, SEXP f1SEXP, SEXP cmtSEXP, SEXP evidSEXP, SEXP ssSEXP, SEXP iiSEXP, SEXP dvSEXP, SEXP obs_idxSEXP, SEXP etaSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP include_omega_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cmt(cmtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type evid(evidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ii(iiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dv(dvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type obs_idx(obs_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type include_omega_prior(include_omega_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_subject_nll_cpp(time, amt, rate, f1, cmt, evid, ss, ii, dv, obs_idx, eta, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior));
    return rcpp_result_gen;
END_RCPP
}
// nm_saem_mh_cpp
NumericMatrix nm_saem_mh_cpp(NumericMatrix eta, List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, int n_mcmc, double step_scale);
RcppExport SEXP _LibeRation_nm_saem_mh_cpp(SEXP etaSEXP, SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP n_mcmcSEXP, SEXP step_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< double >::type step_scale(step_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_saem_mh_cpp(eta, subjects, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_mcmc, step_scale));
    return rcpp_result_gen;
END_RCPP
}
// nm_nll_cpp
double nm_nll_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, NumericMatrix eta, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool include_omega_prior);
RcppExport SEXP _LibeRation_nm_nll_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP etaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP include_omega_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type include_omega_prior(include_omega_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_nll_cpp(subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior));
    return rcpp_result_gen;
END_RCPP
}
// nm_nll_detailed_cpp
List nm_nll_detailed_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, NumericMatrix eta, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool include_omega_prior);
RcppExport SEXP _LibeRation_nm_nll_detailed_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP etaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP include_omega_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type include_omega_prior(include_omega_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_nll_detailed_cpp(subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior));
    return rcpp_result_gen;
END_RCPP
}
// nm_nll_grad_cpp
List nm_nll_grad_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, NumericMatrix eta, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool include_omega_prior, SEXP fwd_cache, bool grad_from_fwd);
RcppExport SEXP _LibeRation_nm_nll_grad_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP etaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP include_omega_priorSEXP, SEXP fwd_cacheSEXP, SEXP grad_from_fwdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type include_omega_prior(include_omega_priorSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fwd_cache(fwd_cacheSEXP);
    Rcpp::traits::input_parameter< bool >::type grad_from_fwd(grad_from_fwdSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_nll_grad_cpp(subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior, fwd_cache, grad_from_fwd));
    return rcpp_result_gen;
END_RCPP
}
// nm_fit_eta_mode_cpp
NumericVector nm_fit_eta_mode_cpp(List subject, NumericVector theta, NumericVector omega, NumericVector sigma, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, SEXP eta_init, int max_iter);
RcppExport SEXP _LibeRation_nm_fit_eta_mode_cpp(SEXP subjectSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP eta_initSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_fit_eta_mode_cpp(subject, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, eta_init, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// nm_fit_all_eta_cpp
NumericMatrix nm_fit_all_eta_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, SEXP eta_init, int max_iter);
RcppExport SEXP _LibeRation_nm_fit_all_eta_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP eta_initSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta_init(eta_initSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_fit_all_eta_cpp(subjects, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, eta_init, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// nm_fo_marginal_cpp
double nm_fo_marginal_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, int n_eta, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss);
RcppExport SEXP _LibeRation_nm_fo_marginal_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP n_etaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n_eta(n_etaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_fo_marginal_cpp(subjects, theta, omega, sigma, n_eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss));
    return rcpp_result_gen;
END_RCPP
}
// nm_focei_objective_cpp
double nm_focei_objective_cpp(List subjects, NumericMatrix eta_modes, NumericVector theta, NumericVector omega, NumericVector sigma, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool interaction);
RcppExport SEXP _LibeRation_nm_focei_objective_cpp(SEXP subjectsSEXP, SEXP eta_modesSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP interactionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eta_modes(eta_modesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type interaction(interactionSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_focei_objective_cpp(subjects, eta_modes, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, interaction));
    return rcpp_result_gen;
END_RCPP
}
// nm_focei_interaction_cpp
double nm_focei_interaction_cpp(List subjects, NumericMatrix eta_modes, NumericVector theta, NumericVector omega, NumericVector sigma, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss);
RcppExport SEXP _LibeRation_nm_focei_interaction_cpp(SEXP subjectsSEXP, SEXP eta_modesSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type eta_modes(eta_modesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_focei_interaction_cpp(subjects, eta_modes, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss));
    return rcpp_result_gen;
END_RCPP
}
// nm_laplace_nll_cpp
double nm_laplace_nll_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, NumericVector gh_nodes, NumericVector gh_weights, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool mode_centered, int n_threads, SEXP eta_modes);
RcppExport SEXP _LibeRation_nm_laplace_nll_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP gh_nodesSEXP, SEXP gh_weightsSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP mode_centeredSEXP, SEXP n_threadsSEXP, SEXP eta_modesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gh_nodes(gh_nodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gh_weights(gh_weightsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type mode_centered(mode_centeredSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta_modes(eta_modesSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_laplace_nll_cpp(subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered, n_threads, eta_modes));
    return rcpp_result_gen;
END_RCPP
}
// nm_laplace_nll_grad_cpp
List nm_laplace_nll_grad_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, NumericVector gh_nodes, NumericVector gh_weights, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool mode_centered, int n_threads, SEXP eta_modes, SEXP fwd_cache, bool grad_from_fwd);
RcppExport SEXP _LibeRation_nm_laplace_nll_grad_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP gh_nodesSEXP, SEXP gh_weightsSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP mode_centeredSEXP, SEXP n_threadsSEXP, SEXP eta_modesSEXP, SEXP fwd_cacheSEXP, SEXP grad_from_fwdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gh_nodes(gh_nodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gh_weights(gh_weightsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type mode_centered(mode_centeredSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta_modes(eta_modesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fwd_cache(fwd_cacheSEXP);
    Rcpp::traits::input_parameter< bool >::type grad_from_fwd(grad_from_fwdSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_laplace_nll_grad_cpp(subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered, n_threads, eta_modes, fwd_cache, grad_from_fwd));
    return rcpp_result_gen;
END_RCPP
}
// nm_laplace_nll_detailed_cpp
List nm_laplace_nll_detailed_cpp(List subjects, NumericVector theta, NumericVector omega, NumericVector sigma, NumericVector gh_nodes, NumericVector gh_weights, CharacterVector pred_lines, int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, bool mode_centered, SEXP eta_modes);
RcppExport SEXP _LibeRation_nm_laplace_nll_detailed_cpp(SEXP subjectsSEXP, SEXP thetaSEXP, SEXP omegaSEXP, SEXP sigmaSEXP, SEXP gh_nodesSEXP, SEXP gh_weightsSEXP, SEXP pred_linesSEXP, SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP mode_centeredSEXP, SEXP eta_modesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gh_nodes(gh_nodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gh_weights(gh_weightsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< bool >::type mode_centered(mode_centeredSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta_modes(eta_modesSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_laplace_nll_detailed_cpp(subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered, eta_modes));
    return rcpp_result_gen;
END_RCPP
}
// nm_lik_config_set
void nm_lik_config_set(int error_type, int omega_type, int sigma_corr, int iov, double ar1_rho, int blq_method);
RcppExport SEXP _LibeRation_nm_lik_config_set(SEXP error_typeSEXP, SEXP omega_typeSEXP, SEXP sigma_corrSEXP, SEXP iovSEXP, SEXP ar1_rhoSEXP, SEXP blq_methodSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type error_type(error_typeSEXP);
    Rcpp::traits::input_parameter< int >::type omega_type(omega_typeSEXP);
    Rcpp::traits::input_parameter< int >::type sigma_corr(sigma_corrSEXP);
    Rcpp::traits::input_parameter< int >::type iov(iovSEXP);
    Rcpp::traits::input_parameter< double >::type ar1_rho(ar1_rhoSEXP);
    Rcpp::traits::input_parameter< int >::type blq_method(blq_methodSEXP);
    nm_lik_config_set(error_type, omega_type, sigma_corr, iov, ar1_rho, blq_method);
    return R_NilValue;
END_RCPP
}
// nm_lik_config_get
Rcpp::List nm_lik_config_get();
RcppExport SEXP _LibeRation_nm_lik_config_get() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(nm_lik_config_get());
    return rcpp_result_gen;
END_RCPP
}
// pk_oral2_trans4_block_var
Environment pk_oral2_trans4_block_var(NumericVector time, NumericVector amt, NumericVector f1, IntegerVector evid, SEXP ka_node, SEXP k20_node, SEXP k23_node, SEXP k32_node, SEXP vc_node, SEXP vp_node, int obs_cmp);
RcppExport SEXP _LibeRation_pk_oral2_trans4_block_var(SEXP timeSEXP, SEXP amtSEXP, SEXP f1SEXP, SEXP evidSEXP, SEXP ka_nodeSEXP, SEXP k20_nodeSEXP, SEXP k23_nodeSEXP, SEXP k32_nodeSEXP, SEXP vc_nodeSEXP, SEXP vp_nodeSEXP, SEXP obs_cmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type evid(evidSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ka_node(ka_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k20_node(k20_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k23_node(k23_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k32_node(k32_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vc_node(vc_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vp_node(vp_nodeSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    rcpp_result_gen = Rcpp::wrap(pk_oral2_trans4_block_var(time, amt, f1, evid, ka_node, k20_node, k23_node, k32_node, vc_node, vp_node, obs_cmp));
    return rcpp_result_gen;
END_RCPP
}
// pk_oral1_block_var
Environment pk_oral1_block_var(NumericVector time, NumericVector amt, NumericVector f1, IntegerVector evid, SEXP ka_node, SEXP k10_node, SEXP v_node, int obs_cmp);
RcppExport SEXP _LibeRation_pk_oral1_block_var(SEXP timeSEXP, SEXP amtSEXP, SEXP f1SEXP, SEXP evidSEXP, SEXP ka_nodeSEXP, SEXP k10_nodeSEXP, SEXP v_nodeSEXP, SEXP obs_cmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type evid(evidSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ka_node(ka_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k10_node(k10_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type v_node(v_nodeSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    rcpp_result_gen = Rcpp::wrap(pk_oral1_block_var(time, amt, f1, evid, ka_node, k10_node, v_node, obs_cmp));
    return rcpp_result_gen;
END_RCPP
}
// pk_bolus1_block_var
Environment pk_bolus1_block_var(NumericVector time, NumericVector amt, IntegerVector evid, SEXP k10_node, SEXP v_node, int obs_cmp);
RcppExport SEXP _LibeRation_pk_bolus1_block_var(SEXP timeSEXP, SEXP amtSEXP, SEXP evidSEXP, SEXP k10_nodeSEXP, SEXP v_nodeSEXP, SEXP obs_cmpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type evid(evidSEXP);
    Rcpp::traits::input_parameter< SEXP >::type k10_node(k10_nodeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type v_node(v_nodeSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    rcpp_result_gen = Rcpp::wrap(pk_bolus1_block_var(time, amt, evid, k10_node, v_node, obs_cmp));
    return rcpp_result_gen;
END_RCPP
}
// nm_pred_expr_check_cpp
bool nm_pred_expr_check_cpp(CharacterVector pred_lines);
RcppExport SEXP _LibeRation_nm_pred_expr_check_cpp(SEXP pred_linesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_pred_expr_check_cpp(pred_lines));
    return rcpp_result_gen;
END_RCPP
}
// nm_eval_pred_cpp
List nm_eval_pred_cpp(CharacterVector pred_lines, NumericVector theta, NumericVector eta, List covariates, CharacterVector des_lines);
RcppExport SEXP _LibeRation_nm_eval_pred_cpp(SEXP pred_linesSEXP, SEXP thetaSEXP, SEXP etaSEXP, SEXP covariatesSEXP, SEXP des_linesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type pred_lines(pred_linesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< List >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type des_lines(des_linesSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_eval_pred_cpp(pred_lines, theta, eta, covariates, des_lines));
    return rcpp_result_gen;
END_RCPP
}
// nm_pk_route_r
NumericVector nm_pk_route_r(int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, NumericVector time, NumericVector amt, NumericVector rate, NumericVector f1, IntegerVector cmt, IntegerVector evid, IntegerVector ss, NumericVector ii, List pk_params, NumericVector s1, NumericVector s2, NumericVector s3, NumericVector s4, NumericMatrix scale_mat, bool use_data_scale, NumericMatrix f_mat, bool use_data_f);
RcppExport SEXP _LibeRation_nm_pk_route_r(SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP timeSEXP, SEXP amtSEXP, SEXP rateSEXP, SEXP f1SEXP, SEXP cmtSEXP, SEXP evidSEXP, SEXP ssSEXP, SEXP iiSEXP, SEXP pk_paramsSEXP, SEXP s1SEXP, SEXP s2SEXP, SEXP s3SEXP, SEXP s4SEXP, SEXP scale_matSEXP, SEXP use_data_scaleSEXP, SEXP f_matSEXP, SEXP use_data_fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cmt(cmtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type evid(evidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ii(iiSEXP);
    Rcpp::traits::input_parameter< List >::type pk_params(pk_paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s3(s3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s4(s4SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type scale_mat(scale_matSEXP);
    Rcpp::traits::input_parameter< bool >::type use_data_scale(use_data_scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type f_mat(f_matSEXP);
    Rcpp::traits::input_parameter< bool >::type use_data_f(use_data_fSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_pk_route_r(advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, time, amt, rate, f1, cmt, evid, ss, ii, pk_params, s1, s2, s3, s4, scale_mat, use_data_scale, f_mat, use_data_f));
    return rcpp_result_gen;
END_RCPP
}
// nm_pk_route_detail_r
List nm_pk_route_detail_r(int advan, int trans, int obs_cmp, int dose_cmp, int n_transit, bool use_ode, int model_ss, int n_state, NumericVector time, NumericVector amt, NumericVector rate, NumericVector f1, IntegerVector cmt, IntegerVector evid, IntegerVector ss, NumericVector ii, List pk_params, NumericVector s1, NumericVector s2, NumericVector s3, NumericVector s4, NumericMatrix scale_mat, bool use_data_scale, NumericMatrix f_mat, bool use_data_f);
RcppExport SEXP _LibeRation_nm_pk_route_detail_r(SEXP advanSEXP, SEXP transSEXP, SEXP obs_cmpSEXP, SEXP dose_cmpSEXP, SEXP n_transitSEXP, SEXP use_odeSEXP, SEXP model_ssSEXP, SEXP n_stateSEXP, SEXP timeSEXP, SEXP amtSEXP, SEXP rateSEXP, SEXP f1SEXP, SEXP cmtSEXP, SEXP evidSEXP, SEXP ssSEXP, SEXP iiSEXP, SEXP pk_paramsSEXP, SEXP s1SEXP, SEXP s2SEXP, SEXP s3SEXP, SEXP s4SEXP, SEXP scale_matSEXP, SEXP use_data_scaleSEXP, SEXP f_matSEXP, SEXP use_data_fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    Rcpp::traits::input_parameter< int >::type obs_cmp(obs_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type dose_cmp(dose_cmpSEXP);
    Rcpp::traits::input_parameter< int >::type n_transit(n_transitSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ode(use_odeSEXP);
    Rcpp::traits::input_parameter< int >::type model_ss(model_ssSEXP);
    Rcpp::traits::input_parameter< int >::type n_state(n_stateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amt(amtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cmt(cmtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type evid(evidSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ii(iiSEXP);
    Rcpp::traits::input_parameter< List >::type pk_params(pk_paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s3(s3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s4(s4SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type scale_mat(scale_matSEXP);
    Rcpp::traits::input_parameter< bool >::type use_data_scale(use_data_scaleSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type f_mat(f_matSEXP);
    Rcpp::traits::input_parameter< bool >::type use_data_f(use_data_fSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_pk_route_detail_r(advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_state, time, amt, rate, f1, cmt, evid, ss, ii, pk_params, s1, s2, s3, s4, scale_mat, use_data_scale, f_mat, use_data_f));
    return rcpp_result_gen;
END_RCPP
}
// nm_cpp_advan_supported
bool nm_cpp_advan_supported(int advan, int trans);
RcppExport SEXP _LibeRation_nm_cpp_advan_supported(SEXP advanSEXP, SEXP transSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type advan(advanSEXP);
    Rcpp::traits::input_parameter< int >::type trans(transSEXP);
    rcpp_result_gen = Rcpp::wrap(nm_cpp_advan_supported(advan, trans));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LibeRation_nm_bayes_mcmc_cpp", (DL_FUNC) &_LibeRation_nm_bayes_mcmc_cpp, 35},
    {"_LibeRation_nm_subject_nll_cpp", (DL_FUNC) &_LibeRation_nm_subject_nll_cpp, 23},
    {"_LibeRation_nm_saem_mh_cpp", (DL_FUNC) &_LibeRation_nm_saem_mh_cpp, 15},
    {"_LibeRation_nm_nll_cpp", (DL_FUNC) &_LibeRation_nm_nll_cpp, 14},
    {"_LibeRation_nm_nll_detailed_cpp", (DL_FUNC) &_LibeRation_nm_nll_detailed_cpp, 14},
    {"_LibeRation_nm_nll_grad_cpp", (DL_FUNC) &_LibeRation_nm_nll_grad_cpp, 16},
    {"_LibeRation_nm_fit_eta_mode_cpp", (DL_FUNC) &_LibeRation_nm_fit_eta_mode_cpp, 14},
    {"_LibeRation_nm_fit_all_eta_cpp", (DL_FUNC) &_LibeRation_nm_fit_all_eta_cpp, 14},
    {"_LibeRation_nm_fo_marginal_cpp", (DL_FUNC) &_LibeRation_nm_fo_marginal_cpp, 13},
    {"_LibeRation_nm_focei_objective_cpp", (DL_FUNC) &_LibeRation_nm_focei_objective_cpp, 14},
    {"_LibeRation_nm_focei_interaction_cpp", (DL_FUNC) &_LibeRation_nm_focei_interaction_cpp, 13},
    {"_LibeRation_nm_laplace_nll_cpp", (DL_FUNC) &_LibeRation_nm_laplace_nll_cpp, 17},
    {"_LibeRation_nm_laplace_nll_grad_cpp", (DL_FUNC) &_LibeRation_nm_laplace_nll_grad_cpp, 19},
    {"_LibeRation_nm_laplace_nll_detailed_cpp", (DL_FUNC) &_LibeRation_nm_laplace_nll_detailed_cpp, 16},
    {"_LibeRation_nm_lik_config_set", (DL_FUNC) &_LibeRation_nm_lik_config_set, 6},
    {"_LibeRation_nm_lik_config_get", (DL_FUNC) &_LibeRation_nm_lik_config_get, 0},
    {"_LibeRation_pk_oral2_trans4_block_var", (DL_FUNC) &_LibeRation_pk_oral2_trans4_block_var, 11},
    {"_LibeRation_pk_oral1_block_var", (DL_FUNC) &_LibeRation_pk_oral1_block_var, 8},
    {"_LibeRation_pk_bolus1_block_var", (DL_FUNC) &_LibeRation_pk_bolus1_block_var, 6},
    {"_LibeRation_nm_pred_expr_check_cpp", (DL_FUNC) &_LibeRation_nm_pred_expr_check_cpp, 1},
    {"_LibeRation_nm_eval_pred_cpp", (DL_FUNC) &_LibeRation_nm_eval_pred_cpp, 5},
    {"_LibeRation_nm_pk_route_r", (DL_FUNC) &_LibeRation_nm_pk_route_r, 24},
    {"_LibeRation_nm_pk_route_detail_r", (DL_FUNC) &_LibeRation_nm_pk_route_detail_r, 25},
    {"_LibeRation_nm_cpp_advan_supported", (DL_FUNC) &_LibeRation_nm_cpp_advan_supported, 2},
    {NULL, NULL, 0}
};

void nm_register_pk_ad_reverse(DllInfo* dll);
RcppExport void R_init_LibeRation(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    nm_register_pk_ad_reverse(dll);
}
