.nm_audit_text <- function(lines) {
  lines <- enc2utf8(as.character(lines %||% character()))
  paste0(paste(lines, collapse = "\n"), "\n")
}

.nm_audit_digest <- function(text) {
  digest::digest(charToRaw(enc2utf8(text)), algo = "sha256", serialize = FALSE)
}

.nm_audit_file <- function(name, lines, media_type = "text/plain") {
  content <- .nm_audit_text(lines)
  list(
    name = as.character(name), media_type = as.character(media_type),
    bytes = length(charToRaw(enc2utf8(content))),
    sha256 = .nm_audit_digest(content), content = content
  )
}

.nm_audit_table_lines <- function(value) {
  if (is.null(value)) return(character())
  value <- as.data.frame(value, stringsAsFactors = FALSE)
  if (!ncol(value)) return(character())
  connection <- textConnection(NULL, "w", local = TRUE, encoding = "UTF-8")
  on.exit(close(connection), add = TRUE)
  utils::write.table(
    value, connection, sep = "\t", row.names = FALSE, col.names = TRUE,
    quote = TRUE, na = ".", qmethod = "double"
  )
  textConnectionValue(connection)
}

.nm_audit_matrix_lines <- function(value, label) {
  value <- as.matrix(value)
  if (!length(value)) return(character())
  if (is.null(rownames(value))) rownames(value) <- paste0("P", seq_len(nrow(value)))
  if (is.null(colnames(value))) colnames(value) <- paste0("P", seq_len(ncol(value)))
  c(
    paste0("; ", label),
    .nm_audit_table_lines(data.frame(
      PARAMETER = rownames(value), value, check.names = FALSE,
      stringsAsFactors = FALSE
    ))
  )
}

.nm_audit_parameter_values <- function(fit) {
  values <- c(fit$theta, fit$omega, fit$sigma)
  names(values) <- c(
    .nm_numbered_names("THETA", length(fit$theta)),
    .nm_numbered_names("OMEGA", length(fit$omega)),
    .nm_numbered_names("SIGMA", length(fit$sigma))
  )
  values
}

.nm_audit_estimation_record <- function(fit) {
  method <- toupper(as.character(fit$method %||% "FOCEI"))
  switch(
    method,
    FO = "METHOD=0",
    FOCE = "METHOD=COND",
    FOCEI = "METHOD=COND INTERACTION",
    LAPLACE = "METHOD=COND LAPLACE",
    ITS = "METHOD=ITS",
    IMP = "METHOD=IMP",
    SAEM = "METHOD=SAEM",
    BAYES = "METHOD=BAYES",
    paste0("; LibeRation method ", method, " has no direct NONMEM record mapping")
  )
}

.nm_audit_control_lines <- function(model, result, operation, details) {
  control <- tryCatch({
    if (identical(operation, "estimate")) {
      nm_control_write(
        model, data = "data.csv",
        estimation = .nm_audit_estimation_record(result),
        covariance = if (!is.null(result$covariance) &&
          !identical(result$covariance$status %||% "completed", "failed")) {
          "PRINT=E"
        } else FALSE
      )
    } else {
      text <- nm_control_write(model, data = "data.csv")
      seed <- as.integer(details$seed %||% 1L)
      paste(text, paste0("$SIMULATION (", seed, ") ONLYSIM"), sep = "\n")
    }
  }, error = identity)
  if (inherits(control, "error")) {
    return(list(
      lines = character(),
      warning = paste("Control-stream representation omitted:", conditionMessage(control))
    ))
  }
  list(
    lines = c(
      "; Generated by LibeRation for audit and interoperability.",
      "; This is not an original NONMEM control stream or output.",
      strsplit(as.character(control), "\n", fixed = TRUE)[[1L]]
    ),
    warning = ""
  )
}

.nm_audit_listing_lines <- function(result, operation, details, warning = "") {
  engine_label <- as.character(details$engine_label %||% "LibeR native")
  header <- c(
    "LibeRation audit listing",
    "========================",
    "Generated by LibeRation; this is not an original NONMEM .lst file.",
    paste("Operation:", operation),
    paste("Engine:", engine_label),
    paste("Generated (UTC):", .nm_workspace_now())
  )
  if (identical(operation, "estimate")) {
    body <- c(
      paste("Method:", .nm_fit_method_label(result)),
      paste("Objective function:", format(result$objective, digits = 16)),
      paste("Convergence code:", result$convergence),
      paste("Iterations:", result$iterations %||% NA_integer_),
      paste("Model fit seconds:", result$timing$model_fit_seconds %||% NA_real_),
      paste("Covariance seconds:", result$timing$covariance_seconds %||% NA_real_),
      "",
      utils::capture.output(print(summary(result)))
    )
  } else {
    body <- c(
      paste("Rows:", nrow(result)),
      paste("Replications:", details$nsim %||% 1L),
      paste("Random seed:", details$seed %||% NA_integer_),
      paste("Parallel cores:", details$n_cores %||% 1L),
      paste("Solver:", attr(result, "solver", exact = TRUE) %||% "C++")
    )
  }
  if (nzchar(warning)) body <- c(body, "", paste("NOTE:", warning))
  c(header, "", body)
}

.nm_audit_ext_lines <- function(fit) {
  parameters <- .nm_audit_parameter_values(fit)
  header <- c("ITERATION", "OBJ", names(parameters))
  values <- c(-1000000000L, fit$objective, unname(parameters))
  c(
    "; NONMEM-style final-estimate table generated from a LibeRation fit.",
    paste(header, collapse = " "),
    paste(format(values, digits = 16, scientific = TRUE, trim = TRUE), collapse = " ")
  )
}

.nm_audit_phi_lines <- function(fit) {
  eta <- nm_etab(fit)$eta
  c(
    "; NONMEM-style subject ETA table generated from a LibeRation fit.",
    .nm_audit_table_lines(eta)
  )
}

.nm_audit_covariance <- function(fit) {
  covariance <- fit$covariance %||% NULL
  if (!is.null(covariance) &&
      !identical(covariance$status %||% "completed", "failed")) {
    return(list(
      covariance = covariance$covariance %||% NULL,
      correlation = covariance$correlation %||% NULL
    ))
  }
  posterior <- fit$posterior$population %||% NULL
  list(
    covariance = posterior$covariance %||% fit$posterior_covariance %||% NULL,
    correlation = posterior$correlation %||% NULL
  )
}

.nm_audit_bundle_validate <- function(bundle, require_content = TRUE) {
  if (!is.list(bundle) || !identical(bundle$schema %||% "", "liberation.audit-artifacts") ||
      !identical(as.integer(bundle$version %||% 0L), 1L) ||
      !is.list(bundle$files)) {
    .nm_stop("Invalid audit-artifact bundle.")
  }
  names <- vapply(bundle$files, function(file) as.character(file$name %||% ""), character(1))
  if (any(!grepl("^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$", names)) || anyDuplicated(names)) {
    .nm_stop("Audit-artifact bundle contains an unsafe or duplicate filename.")
  }
  for (file in bundle$files) {
    content <- file$content %||% NULL
    if (isTRUE(require_content) &&
        (!is.character(content) || length(content) != 1L || is.na(content))) {
      .nm_stop("Audit-artifact content must be one UTF-8 text value.")
    }
    if (!is.null(content)) {
      bytes <- length(charToRaw(enc2utf8(content)))
      if (!identical(as.numeric(file$bytes), as.numeric(bytes)) ||
          !identical(tolower(as.character(file$sha256)), .nm_audit_digest(content))) {
        .nm_stop("Audit artifact failed its declared size or SHA-256 check: ", file$name, ".")
      }
    }
  }
  invisible(bundle)
}

.nm_audit_bundle <- function(result, model, data, operation,
                             details = list(), engine = "liber",
                             source = "generated") {
  operation <- match.arg(operation, c("estimate", "simulate"))
  model <- if (inherits(model, "NMEngine")) model$model else model
  if (!inherits(model, "nm_model")) .nm_stop("Audit artifacts require an nm_model.")
  control <- .nm_audit_control_lines(model, result, operation, details)
  files <- list(
    .nm_audit_file(
      "model.lst",
      .nm_audit_listing_lines(result, operation, details, control$warning)
    )
  )
  if (length(control$lines)) {
    files[[length(files) + 1L]] <- .nm_audit_file("model.ctl", control$lines)
  }
  if (identical(operation, "estimate")) {
    files[[length(files) + 1L]] <- .nm_audit_file("model.ext", .nm_audit_ext_lines(result))
    files[[length(files) + 1L]] <- .nm_audit_file("model.phi", .nm_audit_phi_lines(result))
    matrices <- .nm_audit_covariance(result)
    if (!is.null(matrices$covariance) && length(matrices$covariance)) {
      files[[length(files) + 1L]] <- .nm_audit_file(
        "model.cov", .nm_audit_matrix_lines(matrices$covariance, "Covariance matrix")
      )
    }
    if (!is.null(matrices$correlation) && length(matrices$correlation)) {
      files[[length(files) + 1L]] <- .nm_audit_file(
        "model.cor", .nm_audit_matrix_lines(matrices$correlation, "Correlation matrix")
      )
    }
    table <- result$output %||% NULL
  } else {
    table <- result
  }
  if (!is.null(table) && nrow(as.data.frame(table)) > 0L) {
    files[[length(files) + 1L]] <- .nm_audit_file(
      "model.tab", .nm_audit_table_lines(table), "text/tab-separated-values"
    )
  }
  bundle <- list(
    schema = "liberation.audit-artifacts", version = 1L,
    engine = as.character(engine), source = as.character(source),
    operation = operation, created = .nm_workspace_now(),
    model_sha256 = digest::digest(nm_model_to_contract(model), algo = "sha256"),
    data_sha256 = digest::digest(as.data.frame(data), algo = "sha256"),
    files = files
  )
  .nm_audit_bundle_validate(bundle)
  bundle
}

.nm_attach_audit_artifacts <- function(result, model, data, operation,
                                       details = list()) {
  attr(result, "audit_artifacts") <- .nm_audit_bundle(
    result, model, data, operation, details = details
  )
  result
}

.nm_audit_public_manifest <- function(bundle, relative_path = NULL) {
  .nm_audit_bundle_validate(bundle)
  list(
    schema = bundle$schema, version = bundle$version,
    engine = bundle$engine, source = bundle$source,
    operation = bundle$operation, created = bundle$created,
    model_sha256 = bundle$model_sha256, data_sha256 = bundle$data_sha256,
    relative_path = relative_path,
    files = lapply(bundle$files, function(file) {
      file[c("name", "media_type", "bytes", "sha256")]
    })
  )
}

.nm_audit_write_text <- function(path, text) {
  connection <- file(path, open = "wb")
  on.exit(close(connection), add = TRUE)
  writeBin(charToRaw(enc2utf8(text)), connection)
  invisible(path)
}

.nm_project_materialize_audit <- function(workspace, project, run, bundle) {
  .nm_audit_bundle_validate(bundle)
  project_directory <- .nm_project_path(workspace, project)
  root <- file.path(project_directory, "audit-artifacts")
  if (!dir.exists(root) && !dir.create(root, recursive = TRUE, showWarnings = FALSE)) {
    .nm_stop("Unable to create the project audit-artifact directory.")
  }
  final <- file.path(root, .nm_workspace_component(run, "run id"))
  if (dir.exists(final)) .nm_stop("Audit artifacts already exist for run: ", run, ".")
  temporary <- tempfile("audit-", tmpdir = root)
  if (!dir.create(temporary, showWarnings = FALSE)) {
    .nm_stop("Unable to create an audit-artifact staging directory.")
  }
  published <- FALSE
  on.exit({
    if (dir.exists(temporary)) unlink(temporary, recursive = TRUE, force = TRUE)
    if (!published && dir.exists(final)) unlink(final, recursive = TRUE, force = TRUE)
  }, add = TRUE)
  for (artifact in bundle$files) {
    path <- file.path(temporary, artifact$name)
    .nm_audit_write_text(path, artifact$content)
    actual <- digest::digest(file = path, algo = "sha256", serialize = FALSE)
    if (!identical(actual, artifact$sha256)) {
      .nm_stop("Written audit artifact failed SHA-256 verification: ", artifact$name, ".")
    }
  }
  relative <- file.path("audit-artifacts", basename(final))
  manifest <- .nm_audit_public_manifest(bundle, relative_path = relative)
  manifest_path <- file.path(temporary, "audit-manifest.json")
  jsonlite::write_json(
    manifest, manifest_path, auto_unbox = TRUE, pretty = TRUE,
    null = "null", digits = 17
  )
  if (!file.rename(temporary, final)) {
    .nm_stop("Unable to publish the audit-artifact directory.")
  }
  if (.Platform$OS.type != "windows") {
    Sys.chmod(final, mode = "0700")
    Sys.chmod(list.files(final, full.names = TRUE), mode = "0600")
  }
  published <- TRUE
  manifest$manifest_sha256 <- digest::digest(
    file = file.path(final, "audit-manifest.json"), algo = "sha256",
    serialize = FALSE
  )
  manifest
}

#' Locate and verify audit artifacts for a saved run
#'
#' @param workspace An [nm_workspace()] or workspace path.
#' @param project Project id.
#' @param run Saved estimation or simulation run id.
#' @param verify Verify every recorded SHA-256 digest.
#' @return A list containing the artifact directory, manifest, and file paths.
#' @export
nm_project_audit_artifacts <- function(workspace, project, run, verify = TRUE) {
  workspace <- if (inherits(workspace, "nm_workspace")) workspace else nm_workspace(workspace)
  run <- .nm_workspace_component(run, "run id")
  records <- nm_project_list(workspace, project)
  row <- records[records$id == run & records$entry_type == "run", , drop = FALSE]
  if (!nrow(row)) .nm_stop("Unknown model run: ", run, ".")
  path <- file.path(.nm_project_path(workspace, project), "audit-artifacts", run)
  manifest_path <- file.path(path, "audit-manifest.json")
  if (!file.exists(manifest_path)) return(NULL)
  manifest <- jsonlite::read_json(manifest_path, simplifyVector = FALSE)
  files <- unname(vapply(manifest$files %||% list(), function(file) {
    file.path(path, as.character(file$name))
  }, character(1)))
  if (isTRUE(verify)) {
    for (index in seq_along(files)) {
      expected <- tolower(as.character(manifest$files[[index]]$sha256))
      if (!file.exists(files[[index]]) || !identical(
        digest::digest(file = files[[index]], algo = "sha256", serialize = FALSE),
        expected
      )) .nm_stop("Saved audit artifact failed verification: ", basename(files[[index]]), ".")
    }
  }
  list(path = normalizePath(path, winslash = "/", mustWork = TRUE),
       manifest = manifest, files = files)
}
