#' @keywords internal
.ad_dispatch <- LibeRtAD:::.ad_dispatch
.ad_check_formals <- LibeRtAD:::.ad_check_formals
.ad_values_to_parameters <- LibeRtAD:::.ad_values_to_parameters
.ad_reset_gradients <- LibeRtAD:::.ad_reset_gradients
.ad_make_eval_env <- LibeRtAD:::.ad_make_eval_env
.ad_as_ad_node <- LibeRtAD:::.ad_as_ad_node
.ad_node_len <- LibeRtAD:::.ad_node_len
.ad_run_reverse <- LibeRtAD:::.ad_run_reverse
.ad_collect_reverse_partials <- LibeRtAD:::.ad_collect_reverse_partials
.ad_scalar_value <- LibeRtAD:::.ad_scalar_value
.ad_bind_math_ops <- LibeRtAD:::.ad_bind_math_ops
.ad_bind_control_ops <- LibeRtAD:::.ad_bind_control_ops
.ad_use_cpp <- LibeRtAD:::.ad_use_cpp
set_ops <- LibeRtAD:::set_ops
reset_tape <- LibeRtAD::reset_tape
ad_tape_save <- LibeRtAD::ad_tape_save
ad_tape_load <- LibeRtAD::ad_tape_load
.ad_bind_tape_parameters <- LibeRtAD:::.ad_bind_tape_parameters
replay_tape_values_cpp <- LibeRtAD::replay_tape_values_cpp
reset_tape_grads_cpp <- LibeRtAD::reset_tape_grads_cpp
tape_scalar_value_cpp <- LibeRtAD::tape_scalar_value_cpp
.ad_eval_function <- LibeRtAD:::.ad_eval_function
newConstant <- LibeRtAD::newConstant
newVariable <- LibeRtAD::newVariable
