# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nm_bayes_mcmc_cpp <- function(eta, theta, omega, sigma, subjects, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_burn = 100L, n_sample = 500L, n_thin = 1L, step_theta = numeric(), step_omega = numeric(), step_sigma = numeric(), step_eta = 1.0, theta_prior_type = integer(), theta_prior_mu = numeric(), theta_prior_sd = numeric(), omega_prior_type = integer(), omega_prior_mu = numeric(), omega_prior_sd = numeric(), sigma_prior_type = integer(), sigma_prior_mu = numeric(), sigma_prior_sd = numeric(), theta_fix = logical(), des_lines = character(), sampler = "mh", hmc_epsilon = 0.05, hmc_leap = 10L, nuts_depth = 5L) {
    .Call(`_LibeRation_nm_bayes_mcmc_cpp`, eta, theta, omega, sigma, subjects, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_burn, n_sample, n_thin, step_theta, step_omega, step_sigma, step_eta, theta_prior_type, theta_prior_mu, theta_prior_sd, omega_prior_type, omega_prior_mu, omega_prior_sd, sigma_prior_type, sigma_prior_mu, sigma_prior_sd, theta_fix, des_lines, sampler, hmc_epsilon, hmc_leap, nuts_depth)
}

nm_subject_nll_cpp <- function(time, amt, rate, f1, cmt, evid, ss, ii, dv, obs_idx, eta, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior = TRUE) {
    .Call(`_LibeRation_nm_subject_nll_cpp`, time, amt, rate, f1, cmt, evid, ss, ii, dv, obs_idx, eta, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior)
}

nm_saem_mh_cpp <- function(eta, subjects, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_mcmc = 1L, step_scale = 1.0) {
    .Call(`_LibeRation_nm_saem_mh_cpp`, eta, subjects, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_mcmc, step_scale)
}

nm_nll_cpp <- function(subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior = TRUE) {
    .Call(`_LibeRation_nm_nll_cpp`, subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior)
}

nm_nll_detailed_cpp <- function(subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior = TRUE) {
    .Call(`_LibeRation_nm_nll_detailed_cpp`, subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior)
}

nm_nll_grad_cpp <- function(subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior = TRUE, fwd_cache = NULL, grad_from_fwd = FALSE) {
    .Call(`_LibeRation_nm_nll_grad_cpp`, subjects, theta, omega, sigma, eta, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, include_omega_prior, fwd_cache, grad_from_fwd)
}

nm_fit_eta_mode_cpp <- function(subject, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, eta_init = NULL, max_iter = 200L) {
    .Call(`_LibeRation_nm_fit_eta_mode_cpp`, subject, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, eta_init, max_iter)
}

nm_fit_all_eta_cpp <- function(subjects, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, eta_init = NULL, max_iter = 200L) {
    .Call(`_LibeRation_nm_fit_all_eta_cpp`, subjects, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, eta_init, max_iter)
}

nm_focei_objective_cpp <- function(subjects, eta_modes, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss) {
    .Call(`_LibeRation_nm_focei_objective_cpp`, subjects, eta_modes, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss)
}

nm_focei_interaction_cpp <- function(subjects, eta_modes, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss) {
    .Call(`_LibeRation_nm_focei_interaction_cpp`, subjects, eta_modes, theta, omega, sigma, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss)
}

nm_laplace_nll_cpp <- function(subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered = TRUE, n_threads = 0L, eta_modes = NULL) {
    .Call(`_LibeRation_nm_laplace_nll_cpp`, subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered, n_threads, eta_modes)
}

nm_laplace_nll_grad_cpp <- function(subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered = TRUE, n_threads = 0L, eta_modes = NULL, fwd_cache = NULL, grad_from_fwd = FALSE) {
    .Call(`_LibeRation_nm_laplace_nll_grad_cpp`, subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered, n_threads, eta_modes, fwd_cache, grad_from_fwd)
}

nm_laplace_nll_detailed_cpp <- function(subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered = TRUE, eta_modes = NULL) {
    .Call(`_LibeRation_nm_laplace_nll_detailed_cpp`, subjects, theta, omega, sigma, gh_nodes, gh_weights, pred_lines, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, mode_centered, eta_modes)
}

nm_lik_config_set <- function(error_type = 0L, omega_type = 0L, sigma_corr = 0L, iov = 0L, ar1_rho = 0.0) {
    invisible(.Call(`_LibeRation_nm_lik_config_set`, error_type, omega_type, sigma_corr, iov, ar1_rho))
}

nm_lik_config_get <- function() {
    .Call(`_LibeRation_nm_lik_config_get`)
}

pk_oral2_trans4_block_var <- function(time, amt, f1, evid, ka_node, k20_node, k23_node, k32_node, vc_node, vp_node, obs_cmp) {
    .Call(`_LibeRation_pk_oral2_trans4_block_var`, time, amt, f1, evid, ka_node, k20_node, k23_node, k32_node, vc_node, vp_node, obs_cmp)
}

pk_oral1_block_var <- function(time, amt, f1, evid, ka_node, k10_node, v_node, obs_cmp) {
    .Call(`_LibeRation_pk_oral1_block_var`, time, amt, f1, evid, ka_node, k10_node, v_node, obs_cmp)
}

pk_bolus1_block_var <- function(time, amt, evid, k10_node, v_node, obs_cmp) {
    .Call(`_LibeRation_pk_bolus1_block_var`, time, amt, evid, k10_node, v_node, obs_cmp)
}

nm_pred_expr_check_cpp <- function(pred_lines) {
    .Call(`_LibeRation_nm_pred_expr_check_cpp`, pred_lines)
}

nm_eval_pred_cpp <- function(pred_lines, theta, eta, covariates, des_lines = character()) {
    .Call(`_LibeRation_nm_eval_pred_cpp`, pred_lines, theta, eta, covariates, des_lines)
}

nm_pk_route_r <- function(advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, time, amt, rate, f1, cmt, evid, ss, ii, pk_params, s1 = numeric(), s2 = numeric(), s3 = numeric(), s4 = numeric(), scale_mat = matrix(), use_data_scale = FALSE, f_mat = matrix(), use_data_f = FALSE) {
    .Call(`_LibeRation_nm_pk_route_r`, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, time, amt, rate, f1, cmt, evid, ss, ii, pk_params, s1, s2, s3, s4, scale_mat, use_data_scale, f_mat, use_data_f)
}

nm_pk_route_detail_r <- function(advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_state, time, amt, rate, f1, cmt, evid, ss, ii, pk_params, s1 = numeric(), s2 = numeric(), s3 = numeric(), s4 = numeric(), scale_mat = matrix(), use_data_scale = FALSE, f_mat = matrix(), use_data_f = FALSE) {
    .Call(`_LibeRation_nm_pk_route_detail_r`, advan, trans, obs_cmp, dose_cmp, n_transit, use_ode, model_ss, n_state, time, amt, rate, f1, cmt, evid, ss, ii, pk_params, s1, s2, s3, s4, scale_mat, use_data_scale, f_mat, use_data_f)
}

nm_cpp_advan_supported <- function(advan, trans) {
    .Call(`_LibeRation_nm_cpp_advan_supported`, advan, trans)
}

