# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.liberation_native_optimizer <- function(objective, gradient, start, lower, upper, maxit = 200L, tolerance = 1e-6, trace = 0L) {
    .Call(`_LibeRation_liberation_native_optimizer`, objective, gradient, start, lower, upper, maxit, tolerance, trace)
}

.liberation_population_objective_create <- function(engine_pointer, subject_data, primary_tape_pointers, curvature_tape_pointers, config) {
    .Call(`_LibeRation_liberation_population_objective_create`, engine_pointer, subject_data, primary_tape_pointers, curvature_tape_pointers, config)
}

.liberation_population_objective_value <- function(pointer, encoded) {
    .Call(`_LibeRation_liberation_population_objective_value`, pointer, encoded)
}

.liberation_population_objective_gradient <- function(pointer, encoded) {
    .Call(`_LibeRation_liberation_population_objective_gradient`, pointer, encoded)
}

.liberation_population_objective_state <- function(pointer, encoded) {
    .Call(`_LibeRation_liberation_population_objective_state`, pointer, encoded)
}

.liberation_population_objective_telemetry <- function(pointer) {
    .Call(`_LibeRation_liberation_population_objective_telemetry`, pointer)
}

.liberation_engine_create <- function(specification) {
    .Call(`_LibeRation_liberation_engine_create`, specification)
}

.liberation_engine_simulate <- function(engine_pointer, data, theta, eta, sigma) {
    .Call(`_LibeRation_liberation_engine_simulate`, engine_pointer, data, theta, eta, sigma)
}

.liberation_engine_hmm_filter <- function(engine_pointer, data, theta, eta, sigma) {
    .Call(`_LibeRation_liberation_engine_hmm_filter`, engine_pointer, data, theta, eta, sigma)
}

.liberation_engine_kalman_filter <- function(engine_pointer, data, theta, eta, sigma) {
    .Call(`_LibeRation_liberation_engine_kalman_filter`, engine_pointer, data, theta, eta, sigma)
}

.liberation_engine_kalman_simulate <- function(engine_pointer, data, theta, eta, sigma, process_normals, observation_normals) {
    .Call(`_LibeRation_liberation_engine_kalman_simulate`, engine_pointer, data, theta, eta, sigma, process_normals, observation_normals)
}

.liberation_engine_derivative <- function(engine_pointer, data, row, subject, time, state, theta, eta, sigma) {
    .Call(`_LibeRation_liberation_engine_derivative`, engine_pointer, data, row, subject, time, state, theta, eta, sigma)
}

.liberation_matrix_exp <- function(matrix, dt = 1.0) {
    .Call(`_LibeRation_liberation_matrix_exp`, matrix, dt)
}

.liberation_advan_matrix <- function(advan, parameters) {
    .Call(`_LibeRation_liberation_advan_matrix`, advan, parameters)
}

.liberation_prediction_tape_create <- function(engine_pointer, data, theta, eta, sigma) {
    .Call(`_LibeRation_liberation_prediction_tape_create`, engine_pointer, data, theta, eta, sigma)
}

.liberation_prediction_tape_info <- function(tape_pointer) {
    .Call(`_LibeRation_liberation_prediction_tape_info`, tape_pointer)
}

.liberation_prediction_tape_new_dynamic <- function(tape_pointer, data) {
    .Call(`_LibeRation_liberation_prediction_tape_new_dynamic`, tape_pointer, data)
}

.liberation_fo_tape_new_dynamic <- function(tape_pointer, data) {
    .Call(`_LibeRation_liberation_fo_tape_new_dynamic`, tape_pointer, data)
}

.liberation_prediction_tape_eval <- function(tape_pointer, point, jacobian = TRUE) {
    .Call(`_LibeRation_liberation_prediction_tape_eval`, tape_pointer, point, jacobian)
}

.liberation_prediction_tape_eval_subset <- function(tape_pointer, point, columns) {
    .Call(`_LibeRation_liberation_prediction_tape_eval_subset`, tape_pointer, point, columns)
}

.liberation_matrix_exp_pade <- function(matrix, dt = 1.0) {
    .Call(`_LibeRation_liberation_matrix_exp_pade`, matrix, dt)
}

.liberation_fo_tape_create <- function(engine_pointer, prediction_tape_pointer, data, theta, sigma, omega) {
    .Call(`_LibeRation_liberation_fo_tape_create`, engine_pointer, prediction_tape_pointer, data, theta, sigma, omega)
}

.liberation_curvature_tape_create <- function(engine_pointer, prediction_tape_pointer, objective_tape_pointer, data, theta, eta, sigma, omega, approximation) {
    .Call(`_LibeRation_liberation_curvature_tape_create`, engine_pointer, prediction_tape_pointer, objective_tape_pointer, data, theta, eta, sigma, omega, approximation)
}

.liberation_objective_tape_create <- function(engine_pointer, data, theta, eta, sigma, omega, interaction = TRUE) {
    .Call(`_LibeRation_liberation_objective_tape_create`, engine_pointer, data, theta, eta, sigma, omega, interaction)
}

.liberation_objective_tape_eval <- function(tape_pointer, point, gradient = TRUE, hessian = FALSE) {
    .Call(`_LibeRation_liberation_objective_tape_eval`, tape_pointer, point, gradient, hessian)
}

.liberation_objective_tape_info <- function(tape_pointer) {
    .Call(`_LibeRation_liberation_objective_tape_info`, tape_pointer)
}

.liberation_hmc_target_eval <- function(tape_pointer, q, config) {
    .Call(`_LibeRation_liberation_hmc_target_eval`, tape_pointer, q, config)
}

.liberation_hmc_sample <- function(tape_pointer, config, method, n_warmup, n_sample, n_thin, n_chains, seed, step_size, target_acceptance, adapt_mass, n_leapfrog, max_depth, divergence_threshold, print_every) {
    .Call(`_LibeRation_liberation_hmc_sample`, tape_pointer, config, method, n_warmup, n_sample, n_thin, n_chains, seed, step_size, target_acceptance, adapt_mass, n_leapfrog, max_depth, divergence_threshold, print_every)
}

.liberation_objective_tape_eta_values <- function(tape_pointer, point, eta_positions, eta) {
    .Call(`_LibeRation_liberation_objective_tape_eta_values`, tape_pointer, point, eta_positions, eta)
}

.liberation_objective_tape_collection_values <- function(tape_pointers, points) {
    .Call(`_LibeRation_liberation_objective_tape_collection_values`, tape_pointers, points)
}

.liberation_objective_tape_collection_gradients <- function(tape_pointers, points) {
    .Call(`_LibeRation_liberation_objective_tape_collection_gradients`, tape_pointers, points)
}

.liberation_objective_tape_hessian_subset <- function(tape_pointer, point, row_positions, column_positions) {
    .Call(`_LibeRation_liberation_objective_tape_hessian_subset`, tape_pointer, point, row_positions, column_positions)
}

.liberation_nested_population_gradient <- function(objective_tapes, curvature_tapes, points, eta_positions, population_positions, transform) {
    .Call(`_LibeRation_liberation_nested_population_gradient`, objective_tapes, curvature_tapes, points, eta_positions, population_positions, transform)
}

.liberation_objective_tape_eta_mode <- function(tape_pointer, point, eta_positions, start, maxit = 100L, tolerance = 1e-7, exact_hessian = TRUE) {
    .Call(`_LibeRation_liberation_objective_tape_eta_mode`, tape_pointer, point, eta_positions, start, maxit, tolerance, exact_hessian)
}

.liberation_objective_tape_eta_modes <- function(tape_pointers, points, eta_positions, starts, maxit = 100L, tolerance = 1e-7, exact_hessian = TRUE) {
    .Call(`_LibeRation_liberation_objective_tape_eta_modes`, tape_pointers, points, eta_positions, starts, maxit, tolerance, exact_hessian)
}

.liberation_objective_tape_point_gradients <- function(tape_pointer, points) {
    .Call(`_LibeRation_liberation_objective_tape_point_gradients`, tape_pointer, points)
}

.liberation_objective_tape_eta_metropolis <- function(tape_pointers, points, eta_positions, current_eta, proposal_roots, normals, log_uniforms, mcmc_steps, step_scale = 0.5) {
    .Call(`_LibeRation_liberation_objective_tape_eta_metropolis`, tape_pointers, points, eta_positions, current_eta, proposal_roots, normals, log_uniforms, mcmc_steps, step_scale)
}

.liberation_mixture_component_nll <- function(engine_pointer, data, theta, eta, sigma) {
    .Call(`_LibeRation_liberation_mixture_component_nll`, engine_pointer, data, theta, eta, sigma)
}

